version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_initial_dbms_default__database=authdata
      - NEO4J_server_memory_heap_max_size=12G
      - NEO4J_dbms_memory_transaction_total_max=12G
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_config_strict__validation_enabled=false
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./import_data.cypher:/var/lib/neo4j/import/import_data.cypher
    networks:
      - app-network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    depends_on:
      - neo4j
      - ollama
    ports:
      - "7860:7860"
    volumes:
      - ./src:/app/src
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  ollama_data:

networks:
  app-network:
    driver: bridge